language: python

git:
  depth: false

matrix:
  include:
    - python: '3.6'
      after_success:
      - bash sonar-scanner.sh

services:
  - redis-server

addons:
  sonarqube: true

install:
  - pip install -U setuptools pip
  - pip install -e .[cpphash,redis,uwsgi]

script:
  - python setup.py test
