language: python

python:
  - "2.7"

services:
  - redis-server

install:
  - pip install --upgrade setuptools
  - pip install redis>=2.6
  - pip install jsonpickle>=0.9.3
  - pip install uwsgi>=2.0.0

script:
  - python setup.py nosetests
